using Apps.FlowFit.Models.Dtos;

namespace Apps.FlowFit.Models.Responses;

public class ProjectTemplateResult 
{
    public string Id { get; set; }
    public int? ProjectWorkType { get; set; }
    public int? LanguageSource { get; set; }
    public IEnumerable<int>? TargetLanguageIds { get; set; }
    public bool IsProjectUrgent { get; set; }
    public bool IsWebUrgent { get; set; }
    public bool IsProjectQuote { get; set; }
    public bool IsWebQuote { get; set; }
    public string ProjectJobCode { get; set; }
    public string WebJobCode { get; set; }
    public string? ProjectJobCodeDefaultValue { get; set; }
    public bool IsProjectJobCodeDescription { get; set; }
    public bool IsProjectContact { get; set; }
    public bool IsWebContact { get; set; }
    public bool IsProjectApplicant { get; set; }
    public bool IsWebApplicant { get; set; }
    public bool IsProjectDelivering { get; set; }
    public bool IsWebDelivering { get; set; }
    public bool IsParamIsDefault { get; set; }
    public string? Description { get; set; }
    public string ProjectPO { get; set; }
    public string WebPO { get; set; }
    public string ProjectTypeProject { get; set; }
    public string WebTypeProject { get; set; }
    public string ProjectTargetAudience { get; set; }
    public string WebTargetAudience { get; set; }
    public bool IsProjectGP2 { get; set; }
    public int ProjectModule { get; set; }
    public bool IsWebModule { get; set; }
    public bool IsWebVisibleDeadline { get; set; }
    public bool IsWebShowDeadlineNegociable { get; set; }
    public string ProjectDefaultDeadline { get; set; }
    public string ProjectDomain { get; set; }
    public string WebDomain { get; set; }
    public string ProjectChargeCode { get; set; }
    public string WebChargeCode { get; set; }
    public bool WebNewDocument { get; set; }
    public string ProjectPriority { get; set; }
    public string WebPriority { get; set; }
    public int? DefaultWorkingDaysNumber { get; set; }
    public int? MinimumWorkingDaysNumber { get; set; }
    public string ProjectReadership { get; set; }
    public string WebReadership { get; set; }
    public bool IsWebDocumentIsFinal { get; set; }
    public bool IsCertificationRequired { get; set; }
    public bool IsWebCertificationRequired { get; set; }
    public bool IsPrevProjectNumber { get; set; }
    public bool IsWebPrevProjectNumber { get; set; }
    public bool IsWebSpeakerNote { get; set; }
    public bool IsProjectSpeakerNote { get; set; }
    public string Product { get; set; }
    public string WebProduct { get; set; }
    public string ProductArea { get; set; }
    public string WebProductArea { get; set; }
    public string Pcard { get; set; }
    public string WebPcard { get; set; }
    public bool IsAutomaticArchiving { get; set; }
    public string? ArchivalDocumentRoot { get; set; }
    public string? ArchivalDocumentString { get; set; }
    public string? ArchiveCancelledFolder { get; set; }
    public bool IsAutomaticLogitermAnalysis { get; set; }
    public string? TimeZone { get; set; }
    public bool IsWebTimeZoneIndicator { get; set; }
    public string FolderModelId { get; set; }
    public string? ProjectDocumentNamingPattern { get; set; }
    public string? ProjectWorkDocumentNamingPattern { get; set; }
    public bool IsProjectCloseOnDelivery { get; set; }
    public bool IsWebDisplayWorkStatus { get; set; }
    public bool IsProjectCloseOnLastTaskComplete { get; set; }
    public bool IsAutoLinkNewVersion { get; set; }
    public bool IsWebAllowToCancelProject { get; set; }
    public bool IsWebAllowToChangeDeadline { get; set; }
    public string FinancialPurchaseOrderTemplateId { get; set; }
    public bool IsWebAllowProjectToReopen { get; set; }
    public string? DeadlineHoursAllowed { get; set; }
    public string LogiTermTemplateId { get; set; }
    public string WebDeadline { get; set; }
    public string ProjectManagementDeadline { get; set; }
    public bool IsAllowWeekend { get; set; }
    public bool IsAllowWeekendPM { get; set; }
    public string? DeliveryMode { get; set; }
    public bool IsAttachSource { get; set; }
    public string? ProjectDeadlineHour { get; set; }
    public string IsWebProjectDeadlineHour { get; set; }
    public string? WebhookUrl { get; set; }
    public int ProjectClassification { get; set; }
    public int WebProjectClassification { get; set; }
    public bool WillProjectAutoStart { get; set; }
}